title: Ohio Carpal Tunnel Center
baseURL: https://carpaltunnelcenter.com
languageCode: en-us
theme: carpal-tunnel
disableKinds:
  - taxonomy
  - taxonomyTerm
menu:
  main:
    - URL: /
      name: Home
      weight: 1
    - URL: /our-team
      name: Our Team
      weight: 2
    - URL: /faq
      name: FAQ
      weight: 3
    - URL: /about
      name: About
      weight: 4
params:
  appointment_text: Make an appointment today
  author: modstud.io
  description: The Ohio Carpal Tunnel Center specializes in single-port endoscopic
    carpal tunnel release. Personalized care by our team of experts ensures that
    you are in good hands.
  googleAnalitycsID: UA-426069-3
  images: /assets/images/carpal-tunnel-center.jpg
  logo: assets/images/logo.svg
