title: Carpal Tunnel Center
baseURL: 'https://carpaltunnelcenter.netlify.com/'
languageCode: en-us
theme: carpal-tunnel
disableKinds:
  - taxonomy
  - taxonomyTerm
menu:
  main:
    - URL: /
      name: Home
      weight: 1
    - URL: /our-team
      name: Our Team
      weight: 2
    - URL: /faq
      name: FAQ
      weight: 3
    - URL: /about
      name: About
      weight: 4
params:
  appointment_text: Make an appointment today
  author: modstud.io
  description: This is meta description for this site
  googleAnalitycsID: Your ID
  logo: assets/images/page-images/logo.svg
