baseURL: https://carpaltunnelcenter.netlify.com/
languageCode: en-us
title: Carpal Tunnel Center
theme: carpal-tunnel
disableKinds: ["taxonomy", "taxonomyTerm",]

# navigation
menu:
  main:
    - name: Home
      URL: /
      weight: 1

    - name: Our Team
      URL: /our-team
      weight: 2

    - name: FAQ
      URL: /faq
      weight: 3

    - name: About
      URL: /about
      weight: 4

params:
  logo: assets/images/page-images/logo.svg
  # Meta data
  description: This is meta description
  author: modstud.io
  # Google Analitycs
  googleAnalitycsID: Your ID

  appointment_text: Make an appointment today
