backend:
  name: git-gateway
  branch: master

media_folder: "themes/carpal-tunnel/static/assets/images/page-images"
public_folder: "themes/carpal-tunnel/assets/images/page-images"

collections:
  - label: "Team"
    name: "team"
    files:
      file: "themes/carpal-tunnel/data/team.yml"
      extension: "yml"
    - name: "Homepage_title"
      label: "Homepage Heading Text"
      fields:
        - {label: "Enter Heading", name: "home_title", widget: "string"}
    - name: "members"
      label: "Team Member"
      fields:
        - label: "Members"
          name: "member"
          widget: "list"
          fields:
            - {label: "Name", name: "title", widget: "string"}
            - {label: "Specialty", name: "specialty", widget: "string"}
            - {label: "Text", name: "text", widget: "markdown"}
            - {label: "Link to Linkedin", name: "linkedin_link", widget: "string"}
            - {label: "Photo", name: "image", widget: "file"}
    - name: "staffpage_title"
      label: "Additional Staff Heading Text"
      fields:
        - {label: "Enter Heading", name: "staff_title", widget: "string"}
    - name: "staff_list"
      label: "Additional Staff"
      fields:
        - label: "Members"
          name: "staff"
          widget: "list"
          fields:
            - {label: "Name", name: "title", widget: "string"}
            - {label: "Specialty", name: "specialty", widget: "string"}
            - {label: "Link to Linkedin", name: "linkedin_link", widget: "string"}
            - {label: "Photo", name: "image", widget: "file"}
