backend:
  name: git-gateway
  branch: master

media_folder: "themes/carpal-tunnel/static/assets/images/page-images"
public_folder: "themes/carpal-tunnel/assets/images/page-images"

collections:
  - label: "Team"
    name: "team"
    files:
      - name: "members"
        label: "Members"
        file: "themes/carpal-tunnel/data/team.yml"
        extension: "yml"
        fields:
          - label: "Team Member"
            name: "member"
            widget: "list"
            fields:
              - {label: "Name", name: "title", widget: "string"}
              - {label: "Specialty", name: "specialty", widget: "string"}
